use wgpu::util::DeviceExt;

use crate::DEPTH_FORMAT;

pub const MAX_GRASS: usize = 64000;

/// Instance data layout — matches WGSL GrassInstance struct (32 bytes).
/// Only used for buffer sizing; instances are generated by GPU compute.
#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct GrassInstance {
    pos_scale: [f32; 4],
    color_rotation: [f32; 4],
}

pub struct GrassRenderer {
    // Compute pipeline
    compute_pipeline: wgpu::ComputePipeline,
    compute_bg0: wgpu::BindGroup, // uniforms
    compute_bg1: wgpu::BindGroup, // heightmap
    compute_bg2: wgpu::BindGroup, // output (instances + draw_args)

    // Render pipeline
    render_pipeline: wgpu::RenderPipeline,
    render_instance_bg: wgpu::BindGroup, // instances read-only

    // Geometry
    vertex_buffer: wgpu::Buffer,
    index_buffer: wgpu::Buffer,
    index_count: u32,

    // GPU-driven buffers
    instance_buffer: wgpu::Buffer,  // storage: compute writes, render reads
    indirect_buffer: wgpu::Buffer,  // storage + indirect: draw args
    indirect_reset: wgpu::Buffer,   // copy source to reset indirect each frame
}

impl GrassRenderer {
    pub fn new(
        device: &wgpu::Device,
        surface_format: wgpu::TextureFormat,
        uniform_bgl: &wgpu::BindGroupLayout,
        shadow_bgl: &wgpu::BindGroupLayout,
        uniform_buffer: &wgpu::Buffer,
        heightmap_view: &wgpu::TextureView,
    ) -> Self {
        // --- Blade geometry ---
        let (vertices, indices) = generate_grass_blade();
        let index_count = indices.len() as u32;

        let vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Grass Verts"),
            contents: bytemuck::cast_slice(&vertices),
            usage: wgpu::BufferUsages::VERTEX,
        });

        let index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Grass Idx"),
            contents: bytemuck::cast_slice(&indices),
            usage: wgpu::BufferUsages::INDEX,
        });

        // --- GPU buffers for compute output ---

        // Instance storage: compute writes, render vertex shader reads
        let instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Grass Instances (Storage)"),
            size: (MAX_GRASS * std::mem::size_of::<GrassInstance>()) as u64,
            usage: wgpu::BufferUsages::STORAGE,
            mapped_at_creation: false,
        });

        // Indirect draw args: [index_count, instance_count, first_index, base_vertex, first_instance]
        let indirect_data: [u32; 5] = [index_count, 0, 0, 0, 0];
        let indirect_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Grass Indirect Args"),
            contents: bytemuck::cast_slice(&indirect_data),
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::INDIRECT
                | wgpu::BufferUsages::COPY_DST,
        });

        // Reset buffer: copied to indirect_buffer each frame to zero instance_count
        let indirect_reset = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Grass Indirect Reset"),
            contents: bytemuck::cast_slice(&indirect_data),
            usage: wgpu::BufferUsages::COPY_SRC,
        });

        // --- Compute pipeline ---

        let compute_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Grass Compute Shader"),
            source: wgpu::ShaderSource::Wgsl(include_str!("grass_compute.wgsl").into()),
        });

        // Compute group 0: uniforms (COMPUTE visibility)
        let compute_uniform_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Grass Compute Uniform BGL"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        let compute_bg0 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Grass Compute BG0 (Uniforms)"),
            layout: &compute_uniform_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: uniform_buffer.as_entire_binding(),
            }],
        });

        // Compute group 1: heightmap (COMPUTE visibility)
        let compute_heightmap_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Grass Compute Heightmap BGL"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: false },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                }],
            });

        let compute_bg1 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Grass Compute BG1 (Heightmap)"),
            layout: &compute_heightmap_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(heightmap_view),
            }],
        });

        // Compute group 2: output storage buffers (instances + draw_args)
        let compute_output_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Grass Compute Output BGL"),
                entries: &[
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::COMPUTE,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: false },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::COMPUTE,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: false },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                ],
            });

        let compute_bg2 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Grass Compute BG2 (Output)"),
            layout: &compute_output_bgl,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: instance_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: indirect_buffer.as_entire_binding(),
                },
            ],
        });

        let compute_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Grass Compute Layout"),
                bind_group_layouts: &[&compute_uniform_bgl, &compute_heightmap_bgl, &compute_output_bgl],
                push_constant_ranges: &[],
            });

        let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("Grass Compute Pipeline"),
            layout: Some(&compute_pipeline_layout),
            module: &compute_shader,
            entry_point: Some("cs_main"),
            compilation_options: Default::default(),
            cache: None,
        });

        // --- Render pipeline ---

        let render_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Grass Render Shader"),
            source: wgpu::ShaderSource::Wgsl(
                format!(
                    "{}\n{}",
                    include_str!("common.wgsl"),
                    include_str!("grass.wgsl")
                )
                .into(),
            ),
        });

        // Render group 2: instance storage (read-only for vertex shader)
        let render_instance_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Grass Render Instance BGL"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        let render_instance_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Grass Render Instance BG"),
            layout: &render_instance_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: instance_buffer.as_entire_binding(),
            }],
        });

        let render_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Grass Render Layout"),
                bind_group_layouts: &[uniform_bgl, shadow_bgl, &render_instance_bgl],
                push_constant_ranges: &[],
            });

        let render_pipeline = device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
            label: Some("Grass Render Pipeline"),
            layout: Some(&render_pipeline_layout),
            vertex: wgpu::VertexState {
                module: &render_shader,
                entry_point: Some("vs_main"),
                buffers: &[
                    // Per-vertex only: position (vec3) + bend (f32) = 16 bytes
                    wgpu::VertexBufferLayout {
                        array_stride: 16,
                        step_mode: wgpu::VertexStepMode::Vertex,
                        attributes: &[
                            wgpu::VertexAttribute {
                                format: wgpu::VertexFormat::Float32x3,
                                offset: 0,
                                shader_location: 0,
                            },
                            wgpu::VertexAttribute {
                                format: wgpu::VertexFormat::Float32,
                                offset: 12,
                                shader_location: 1,
                            },
                        ],
                    },
                    // No per-instance vertex buffer — instances come from storage buffer
                ],
                compilation_options: Default::default(),
            },
            fragment: Some(wgpu::FragmentState {
                module: &render_shader,
                entry_point: Some("fs_main"),
                targets: &[Some(wgpu::ColorTargetState {
                    format: surface_format,
                    blend: None,
                    write_mask: wgpu::ColorWrites::ALL,
                })],
                compilation_options: Default::default(),
            }),
            primitive: wgpu::PrimitiveState {
                topology: wgpu::PrimitiveTopology::TriangleList,
                front_face: wgpu::FrontFace::Ccw,
                cull_mode: None, // grass blades visible from both sides
                ..Default::default()
            },
            depth_stencil: Some(wgpu::DepthStencilState {
                format: DEPTH_FORMAT,
                depth_write_enabled: true,
                depth_compare: wgpu::CompareFunction::Less,
                stencil: Default::default(),
                bias: Default::default(),
            }),
            multisample: Default::default(),
            multiview: None,
            cache: None,
        });

        log::info!("Grass renderer: GPU compute + indirect draw (max {})", MAX_GRASS);

        Self {
            compute_pipeline,
            compute_bg0,
            compute_bg1,
            compute_bg2,
            render_pipeline,
            render_instance_bg,
            vertex_buffer,
            index_buffer,
            index_count,
            instance_buffer,
            indirect_buffer,
            indirect_reset,
        }
    }

    /// Reset indirect args and dispatch compute shader to generate grass instances.
    /// Must be called before the render pass that draws grass.
    pub fn compute(&self, encoder: &mut wgpu::CommandEncoder) {
        // Reset indirect draw args: [index_count, 0, 0, 0, 0]
        encoder.copy_buffer_to_buffer(&self.indirect_reset, 0, &self.indirect_buffer, 0, 20);

        // Dispatch compute: 320x320 grid, 16x16 workgroups
        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("Grass Compute"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.compute_pipeline);
        pass.set_bind_group(0, &self.compute_bg0, &[]);
        pass.set_bind_group(1, &self.compute_bg1, &[]);
        pass.set_bind_group(2, &self.compute_bg2, &[]);
        pass.dispatch_workgroups(20, 20, 1); // ceil(320/16) = 20
    }

    /// Draw grass using indirect draw — instance count determined by compute shader.
    pub fn draw<'a>(
        &'a self,
        pass: &mut wgpu::RenderPass<'a>,
        uniform_bg: &'a wgpu::BindGroup,
        shadow_bg: &'a wgpu::BindGroup,
    ) {
        pass.set_pipeline(&self.render_pipeline);
        pass.set_bind_group(0, uniform_bg, &[]);
        pass.set_bind_group(1, shadow_bg, &[]);
        pass.set_bind_group(2, &self.render_instance_bg, &[]);
        pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
        pass.set_index_buffer(self.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
        pass.draw_indexed_indirect(&self.indirect_buffer, 0);
    }
}

/// Vertex with position and bend factor (0 at base, 1 at tip).
type GrassVertex = [f32; 4]; // [x, y, z, bend]

/// Generate a curved grass blade: 3 segments (base -> mid -> tip), 6 vertices, 4 triangles.
fn generate_grass_blade() -> (Vec<GrassVertex>, Vec<u32>) {
    let base_hw = 0.12; // half-width at base — narrower for dense fields
    let mid_hw = 0.08;
    let tip_hw = 0.02;
    let mid_h = 0.40;
    let tip_h = 1.0;
    let lean = 0.04;

    let verts = vec![
        [-base_hw, 0.0, 0.0, 0.0],            // 0: base-left (anchored)
        [base_hw, 0.0, 0.0, 0.0],             // 1: base-right (anchored)
        [-mid_hw + lean, mid_h, 0.0, 0.4],    // 2: mid-left (partial bend)
        [mid_hw + lean, mid_h, 0.0, 0.4],     // 3: mid-right (partial bend)
        [-tip_hw + lean, tip_h, 0.0, 1.0],    // 4: tip-left (full bend)
        [tip_hw + lean, tip_h, 0.0, 1.0],     // 5: tip-right (full bend)
    ];

    let indices = vec![
        0, 1, 2, 1, 3, 2, // base quad
        2, 3, 4, 3, 5, 4, // tip quad
    ];

    (verts, indices)
}
