mod terrain;
mod player;
mod rocks;
mod trees;
mod grass;
mod scatter;
mod atmosphere;
mod sky;
mod postprocess;
mod shadow;
mod ssao;
mod pipeline;
mod frame;
pub(crate) mod instanced_mesh;

pub use terrain::{TerrainRenderer, Uniforms, create_depth_texture, DEPTH_FORMAT};
pub use player::{PlayerRenderer, PlayerInstance, player_color};
pub use rocks::{RockRenderer, RockInstance};
pub use trees::{TreeRenderer, TreeInstance};
pub use grass::GrassRenderer;
pub use scatter::scatter_objects;
pub use atmosphere::{AtmosphereParams, compute_atmosphere};
pub use sky::SkyRenderer;
pub use postprocess::{PostProcessRenderer, INTERMEDIATE_FORMAT};
pub use shadow::{create_shadow_texture, create_shadow_bgl, create_shadow_bind_group, compute_sun_view_proj};
pub use ssao::SsaoRenderer;
pub use frame::{SceneRenderers, encode_frame};
pub use pipeline::{create_scene_pipeline, create_shadow_pipeline, create_fullscreen_pipeline, SHADOW_DEPTH_BIAS};
