use wgpu::util::DeviceExt;

const MAX_ROCKS: usize = 4096;

/// Instance data layout — matches WGSL RockInstance struct (32 bytes).
/// Only used for buffer sizing; instances are generated by GPU compute.
#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct RockInstance {
    pos_scale: [f32; 4],
    color: [f32; 4],
}

pub struct RockRenderer {
    // Compute pipeline
    compute_pipeline: wgpu::ComputePipeline,
    compute_bg0: wgpu::BindGroup,
    compute_bg1: wgpu::BindGroup,
    compute_bg2: wgpu::BindGroup,

    // Render pipelines
    render_pipeline: wgpu::RenderPipeline,
    shadow_pipeline: wgpu::RenderPipeline,
    render_instance_bg: wgpu::BindGroup,
    shadow_instance_bg: wgpu::BindGroup,

    // Geometry
    vertex_buffer: wgpu::Buffer,
    index_buffer: wgpu::Buffer,

    // GPU-driven buffers
    indirect_buffer: wgpu::Buffer,
    indirect_reset: wgpu::Buffer,
}

impl RockRenderer {
    pub fn new(
        device: &wgpu::Device,
        surface_format: wgpu::TextureFormat,
        uniform_bgl: &wgpu::BindGroupLayout,
        shadow_bgl: &wgpu::BindGroupLayout,
        uniform_buffer: &wgpu::Buffer,
        heightmap_view: &wgpu::TextureView,
    ) -> Self {
        // --- Rock geometry ---
        let (vertices, indices) = generate_rock_mesh(1.0, 1, 42);
        let index_count = indices.len() as u32;

        let vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Rock Verts"),
            contents: bytemuck::cast_slice(&vertices),
            usage: wgpu::BufferUsages::VERTEX,
        });

        let index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Rock Idx"),
            contents: bytemuck::cast_slice(&indices),
            usage: wgpu::BufferUsages::INDEX,
        });

        // --- GPU buffers for compute output ---

        let instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Rock Instances (Storage)"),
            size: (MAX_ROCKS * std::mem::size_of::<RockInstance>()) as u64,
            usage: wgpu::BufferUsages::STORAGE,
            mapped_at_creation: false,
        });

        let indirect_data: [u32; 5] = [index_count, 0, 0, 0, 0];
        let indirect_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Rock Indirect Args"),
            contents: bytemuck::cast_slice(&indirect_data),
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::INDIRECT
                | wgpu::BufferUsages::COPY_DST,
        });

        let indirect_reset = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Rock Indirect Reset"),
            contents: bytemuck::cast_slice(&indirect_data),
            usage: wgpu::BufferUsages::COPY_SRC,
        });

        // --- Compute pipeline ---

        let compute_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Rock Compute Shader"),
            source: wgpu::ShaderSource::Wgsl(
                format!("{}\n{}\n{}", include_str!("uniforms.wgsl"), include_str!("noise.wgsl"), include_str!("rocks_compute.wgsl")).into(),
            ),
        });

        let compute_bg0 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Rock Compute BG0 (Uniforms)"),
            layout: uniform_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: uniform_buffer.as_entire_binding(),
            }],
        });

        let compute_heightmap_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Rock Compute Heightmap BGL"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: false },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                }],
            });

        let compute_bg1 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Rock Compute BG1 (Heightmap)"),
            layout: &compute_heightmap_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(heightmap_view),
            }],
        });

        let compute_output_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Rock Compute Output BGL"),
                entries: &[
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::COMPUTE,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: false },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::COMPUTE,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: false },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                ],
            });

        let compute_bg2 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Rock Compute BG2 (Output)"),
            layout: &compute_output_bgl,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: instance_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: indirect_buffer.as_entire_binding(),
                },
            ],
        });

        let compute_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Rock Compute Layout"),
                bind_group_layouts: &[uniform_bgl, &compute_heightmap_bgl, &compute_output_bgl],
                push_constant_ranges: &[],
            });

        let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("Rock Compute Pipeline"),
            layout: Some(&compute_pipeline_layout),
            module: &compute_shader,
            entry_point: Some("cs_main"),
            compilation_options: Default::default(),
            cache: None,
        });

        // --- Render pipelines ---

        let render_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Rock Render Shader"),
            source: wgpu::ShaderSource::Wgsl(
                format!(
                    "{}\n{}\n{}\n{}",
                    include_str!("uniforms.wgsl"),
                    include_str!("noise.wgsl"),
                    include_str!("common.wgsl"),
                    include_str!("rocks.wgsl")
                )
                .into(),
            ),
        });

        let render_instance_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Rock Render Instance BGL"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        let render_instance_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Rock Render Instance BG"),
            layout: &render_instance_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: instance_buffer.as_entire_binding(),
            }],
        });

        let shadow_instance_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Rock Shadow Instance BG"),
            layout: &render_instance_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: instance_buffer.as_entire_binding(),
            }],
        });

        let rock_vertex_layout = &[wgpu::VertexBufferLayout {
            array_stride: 12,
            step_mode: wgpu::VertexStepMode::Vertex,
            attributes: &[wgpu::VertexAttribute { format: wgpu::VertexFormat::Float32x3, offset: 0, shader_location: 0 }],
        }];

        // Scene pipeline: group 0=uniforms, 1=shadow, 2=instances
        let render_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Rock Render Layout"),
                bind_group_layouts: &[uniform_bgl, shadow_bgl, &render_instance_bgl],
                push_constant_ranges: &[],
            });

        let render_pipeline = crate::pipeline::create_scene_pipeline(
            device, "Rock Pipeline", &render_shader, &render_pipeline_layout,
            rock_vertex_layout, surface_format,
            Some(wgpu::Face::Back), wgpu::CompareFunction::Less,
        );

        // Shadow pipeline: group 0=uniforms, 1=instances
        let shadow_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Rock Shadow Layout"),
                bind_group_layouts: &[uniform_bgl, &render_instance_bgl],
                push_constant_ranges: &[],
            });

        let shadow_pipeline = crate::pipeline::create_shadow_pipeline(
            device, "Rock Shadow Pipeline", &render_shader, &shadow_pipeline_layout,
            rock_vertex_layout,
        );

        log::info!("Rock renderer: GPU compute + indirect draw (max {})", MAX_ROCKS);

        Self {
            compute_pipeline,
            compute_bg0,
            compute_bg1,
            compute_bg2,
            render_pipeline,
            shadow_pipeline,
            render_instance_bg,
            shadow_instance_bg,
            vertex_buffer,
            index_buffer,
            indirect_buffer,
            indirect_reset,
        }
    }

    /// Reset indirect args and dispatch compute shader to generate rock instances.
    pub fn compute(&self, encoder: &mut wgpu::CommandEncoder) {
        encoder.copy_buffer_to_buffer(&self.indirect_reset, 0, &self.indirect_buffer, 0, 20);

        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("Rock Compute"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.compute_pipeline);
        pass.set_bind_group(0, &self.compute_bg0, &[]);
        pass.set_bind_group(1, &self.compute_bg1, &[]);
        pass.set_bind_group(2, &self.compute_bg2, &[]);
        pass.dispatch_workgroups(6, 6, 1); // ceil(96/16) = 6
    }

    /// Draw rocks using indirect draw — instance count from compute shader.
    pub fn draw<'a>(
        &'a self,
        pass: &mut wgpu::RenderPass<'a>,
        uniform_bg: &'a wgpu::BindGroup,
        shadow_bg: &'a wgpu::BindGroup,
    ) {
        pass.set_pipeline(&self.render_pipeline);
        pass.set_bind_group(0, uniform_bg, &[]);
        pass.set_bind_group(1, shadow_bg, &[]);
        pass.set_bind_group(2, &self.render_instance_bg, &[]);
        pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
        pass.set_index_buffer(self.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
        pass.draw_indexed_indirect(&self.indirect_buffer, 0);
    }

    /// Draw rock shadows using indirect draw.
    pub fn draw_shadow<'a>(
        &'a self,
        pass: &mut wgpu::RenderPass<'a>,
        uniform_bg: &'a wgpu::BindGroup,
    ) {
        pass.set_pipeline(&self.shadow_pipeline);
        pass.set_bind_group(0, uniform_bg, &[]);
        pass.set_bind_group(1, &self.shadow_instance_bg, &[]);
        pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
        pass.set_index_buffer(self.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
        pass.draw_indexed_indirect(&self.indirect_buffer, 0);
    }
}

/// Generate a deformed icosphere rock mesh.
fn generate_rock_mesh(radius: f32, subdivisions: u32, seed: u32) -> (Vec<[f32; 3]>, Vec<u32>) {
    let (mut verts, indices) = icosphere(subdivisions);

    for (i, v) in verts.iter_mut().enumerate() {
        let n = glam::Vec3::from(*v).normalize();
        let hash = simple_hash(seed.wrapping_add(i as u32));
        let displacement = (hash as f32 / u32::MAX as f32) * 0.6 - 0.3;
        let r = radius * (1.0 + displacement);
        *v = (n * r).to_array();
    }

    (verts, indices)
}

fn icosphere(subdivisions: u32) -> (Vec<[f32; 3]>, Vec<u32>) {
    let t = (1.0 + 5.0_f32.sqrt()) / 2.0;

    let mut verts: Vec<glam::Vec3> = vec![
        glam::Vec3::new(-1.0, t, 0.0).normalize(),
        glam::Vec3::new(1.0, t, 0.0).normalize(),
        glam::Vec3::new(-1.0, -t, 0.0).normalize(),
        glam::Vec3::new(1.0, -t, 0.0).normalize(),
        glam::Vec3::new(0.0, -1.0, t).normalize(),
        glam::Vec3::new(0.0, 1.0, t).normalize(),
        glam::Vec3::new(0.0, -1.0, -t).normalize(),
        glam::Vec3::new(0.0, 1.0, -t).normalize(),
        glam::Vec3::new(t, 0.0, -1.0).normalize(),
        glam::Vec3::new(t, 0.0, 1.0).normalize(),
        glam::Vec3::new(-t, 0.0, -1.0).normalize(),
        glam::Vec3::new(-t, 0.0, 1.0).normalize(),
    ];

    let mut indices: Vec<[u32; 3]> = vec![
        [0, 11, 5], [0, 5, 1], [0, 1, 7], [0, 7, 10], [0, 10, 11],
        [1, 5, 9], [5, 11, 4], [11, 10, 2], [10, 7, 6], [7, 1, 8],
        [3, 9, 4], [3, 4, 2], [3, 2, 6], [3, 6, 8], [3, 8, 9],
        [4, 9, 5], [2, 4, 11], [6, 2, 10], [8, 6, 7], [9, 8, 1],
    ];

    use std::collections::HashMap;
    let mut midpoint_cache: HashMap<(u32, u32), u32> = HashMap::new();

    for _ in 0..subdivisions {
        let mut new_indices = Vec::with_capacity(indices.len() * 4);
        midpoint_cache.clear();

        for tri in &indices {
            let a = get_midpoint(&mut verts, &mut midpoint_cache, tri[0], tri[1]);
            let b = get_midpoint(&mut verts, &mut midpoint_cache, tri[1], tri[2]);
            let c = get_midpoint(&mut verts, &mut midpoint_cache, tri[2], tri[0]);

            new_indices.push([tri[0], a, c]);
            new_indices.push([tri[1], b, a]);
            new_indices.push([tri[2], c, b]);
            new_indices.push([a, b, c]);
        }

        indices = new_indices;
    }

    let out_verts: Vec<[f32; 3]> = verts.iter().map(|v| v.to_array()).collect();
    let out_indices: Vec<u32> = indices.iter().flat_map(|t| t.iter().copied()).collect();
    (out_verts, out_indices)
}

fn get_midpoint(
    verts: &mut Vec<glam::Vec3>,
    cache: &mut std::collections::HashMap<(u32, u32), u32>,
    a: u32,
    b: u32,
) -> u32 {
    let key = if a < b { (a, b) } else { (b, a) };
    if let Some(&idx) = cache.get(&key) {
        return idx;
    }
    let mid = ((verts[a as usize] + verts[b as usize]) * 0.5).normalize();
    let idx = verts.len() as u32;
    verts.push(mid);
    cache.insert(key, idx);
    idx
}

fn simple_hash(mut x: u32) -> u32 {
    x = x.wrapping_mul(0x9e3779b9);
    x ^= x >> 16;
    x = x.wrapping_mul(0x85ebca6b);
    x ^= x >> 13;
    x = x.wrapping_mul(0xc2b2ae35);
    x ^= x >> 16;
    x
}
