use wgpu::util::DeviceExt;

pub const MAX_TREES: usize = 8192;

/// Instance data layout — matches WGSL TreeInstance struct (32 bytes).
/// Only used for buffer sizing; instances are generated by GPU compute.
#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct TreeInstance {
    pos_scale: [f32; 4],
    foliage_color: [f32; 4],
}

pub struct TreeRenderer {
    // Compute pipeline
    compute_pipeline: wgpu::ComputePipeline,
    compute_bg0: wgpu::BindGroup, // uniforms
    compute_bg1: wgpu::BindGroup, // heightmap
    compute_bg2: wgpu::BindGroup, // output (instances + draw_args)

    // Render pipelines
    render_pipeline: wgpu::RenderPipeline,
    shadow_pipeline: wgpu::RenderPipeline,
    render_instance_bg: wgpu::BindGroup,  // instances read-only (scene: group 2)
    shadow_instance_bg: wgpu::BindGroup,  // instances read-only (shadow: group 1)

    // Geometry
    vertex_buffer: wgpu::Buffer,
    index_buffer: wgpu::Buffer,

    // GPU-driven buffers
    indirect_buffer: wgpu::Buffer,
    indirect_reset: wgpu::Buffer,
}

impl TreeRenderer {
    pub fn new(
        device: &wgpu::Device,
        surface_format: wgpu::TextureFormat,
        uniform_bgl: &wgpu::BindGroupLayout,
        shadow_bgl: &wgpu::BindGroupLayout,
        uniform_buffer: &wgpu::Buffer,
        heightmap_view: &wgpu::TextureView,
        atlas_bgl: &wgpu::BindGroupLayout,
    ) -> Self {
        // --- Tree geometry ---
        let (vertices, indices) = generate_tree_mesh(12);
        let index_count = indices.len() as u32;

        let vertex_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Tree Verts"),
            contents: bytemuck::cast_slice(&vertices),
            usage: wgpu::BufferUsages::VERTEX,
        });

        let index_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Tree Idx"),
            contents: bytemuck::cast_slice(&indices),
            usage: wgpu::BufferUsages::INDEX,
        });

        // --- GPU buffers for compute output ---

        let instance_buffer = device.create_buffer(&wgpu::BufferDescriptor {
            label: Some("Tree Instances (Storage)"),
            size: (MAX_TREES * std::mem::size_of::<TreeInstance>()) as u64,
            usage: wgpu::BufferUsages::STORAGE,
            mapped_at_creation: false,
        });

        let indirect_data: [u32; 5] = [index_count, 0, 0, 0, 0];
        let indirect_buffer = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Tree Indirect Args"),
            contents: bytemuck::cast_slice(&indirect_data),
            usage: wgpu::BufferUsages::STORAGE
                | wgpu::BufferUsages::INDIRECT
                | wgpu::BufferUsages::COPY_DST,
        });

        let indirect_reset = device.create_buffer_init(&wgpu::util::BufferInitDescriptor {
            label: Some("Tree Indirect Reset"),
            contents: bytemuck::cast_slice(&indirect_data),
            usage: wgpu::BufferUsages::COPY_SRC,
        });

        // --- Compute pipeline ---

        let compute_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Tree Compute Shader"),
            source: wgpu::ShaderSource::Wgsl(
                format!("{}\n{}\n{}\n{}", include_str!("uniforms.wgsl"), include_str!("noise.wgsl"), include_str!("heightmap_utils.wgsl"), include_str!("trees_compute.wgsl")).into(),
            ),
        });

        let compute_bg0 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Tree Compute BG0 (Uniforms)"),
            layout: uniform_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: uniform_buffer.as_entire_binding(),
            }],
        });

        let compute_heightmap_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Tree Compute Heightmap BGL"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: false },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                }],
            });

        let compute_bg1 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Tree Compute BG1 (Heightmap)"),
            layout: &compute_heightmap_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: wgpu::BindingResource::TextureView(heightmap_view),
            }],
        });

        let compute_output_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Tree Compute Output BGL"),
                entries: &[
                    wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::COMPUTE,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: false },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                    wgpu::BindGroupLayoutEntry {
                        binding: 1,
                        visibility: wgpu::ShaderStages::COMPUTE,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: false },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    },
                ],
            });

        let compute_bg2 = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Tree Compute BG2 (Output)"),
            layout: &compute_output_bgl,
            entries: &[
                wgpu::BindGroupEntry {
                    binding: 0,
                    resource: instance_buffer.as_entire_binding(),
                },
                wgpu::BindGroupEntry {
                    binding: 1,
                    resource: indirect_buffer.as_entire_binding(),
                },
            ],
        });

        let compute_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Tree Compute Layout"),
                bind_group_layouts: &[uniform_bgl, &compute_heightmap_bgl, &compute_output_bgl],
                push_constant_ranges: &[],
            });

        let compute_pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some("Tree Compute Pipeline"),
            layout: Some(&compute_pipeline_layout),
            module: &compute_shader,
            entry_point: Some("cs_main"),
            compilation_options: Default::default(),
            cache: None,
        });

        // --- Render pipelines ---

        let render_shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("Tree Render Shader"),
            source: wgpu::ShaderSource::Wgsl(
                format!(
                    "{}\n{}\n{}\n{}\n{}",
                    include_str!("uniforms.wgsl"),
                    include_str!("noise.wgsl"),
                    include_str!("common.wgsl"),
                    include_str!("triplanar.wgsl"),
                    include_str!("trees.wgsl")
                )
                .into(),
            ),
        });

        // Instance storage BGL (read-only, VERTEX visibility)
        let render_instance_bgl =
            device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                label: Some("Tree Render Instance BGL"),
                entries: &[wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::VERTEX,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Storage { read_only: true },
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                }],
            });

        let render_instance_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Tree Render Instance BG"),
            layout: &render_instance_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: instance_buffer.as_entire_binding(),
            }],
        });

        // Shadow also needs instances — same BGL, same buffer, bound at group 1
        let shadow_instance_bg = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some("Tree Shadow Instance BG"),
            layout: &render_instance_bgl,
            entries: &[wgpu::BindGroupEntry {
                binding: 0,
                resource: instance_buffer.as_entire_binding(),
            }],
        });

        let tree_vertex_layout = &[wgpu::VertexBufferLayout {
            array_stride: 36,
            step_mode: wgpu::VertexStepMode::Vertex,
            attributes: &[
                wgpu::VertexAttribute { format: wgpu::VertexFormat::Float32x3, offset: 0, shader_location: 0 },  // position
                wgpu::VertexAttribute { format: wgpu::VertexFormat::Float32x3, offset: 12, shader_location: 1 }, // normal
                wgpu::VertexAttribute { format: wgpu::VertexFormat::Float32x3, offset: 24, shader_location: 2 }, // color
            ],
        }];

        // Scene pipeline: group 0=uniforms, 1=shadow, 2=instances, 3=atlas
        let render_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Tree Render Layout"),
                bind_group_layouts: &[uniform_bgl, shadow_bgl, &render_instance_bgl, atlas_bgl],
                push_constant_ranges: &[],
            });

        let render_pipeline = crate::pipeline::create_scene_pipeline(
            device, "Tree Pipeline", &render_shader, &render_pipeline_layout,
            tree_vertex_layout, surface_format,
            None, wgpu::CompareFunction::Less, // two-sided: visible from inside/below
        );

        // Shadow pipeline: group 0=uniforms, 1=instances
        let shadow_pipeline_layout =
            device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("Tree Shadow Layout"),
                bind_group_layouts: &[uniform_bgl, &render_instance_bgl],
                push_constant_ranges: &[],
            });

        let shadow_pipeline = crate::pipeline::create_shadow_pipeline(
            device, "Tree Shadow Pipeline", &render_shader, &shadow_pipeline_layout,
            tree_vertex_layout,
        );

        log::info!("Tree renderer: GPU compute + indirect draw (max {})", MAX_TREES);

        Self {
            compute_pipeline,
            compute_bg0,
            compute_bg1,
            compute_bg2,
            render_pipeline,
            shadow_pipeline,
            render_instance_bg,
            shadow_instance_bg,
            vertex_buffer,
            index_buffer,
            indirect_buffer,
            indirect_reset,
        }
    }

    /// Reset indirect args and dispatch compute shader to generate tree instances.
    pub fn compute(&self, encoder: &mut wgpu::CommandEncoder) {
        encoder.copy_buffer_to_buffer(&self.indirect_reset, 0, &self.indirect_buffer, 0, 20);

        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some("Tree Compute"),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.compute_pipeline);
        pass.set_bind_group(0, &self.compute_bg0, &[]);
        pass.set_bind_group(1, &self.compute_bg1, &[]);
        pass.set_bind_group(2, &self.compute_bg2, &[]);
        pass.dispatch_workgroups(8, 8, 1); // ceil(128/16) = 8
    }

    /// Draw trees using indirect draw — instance count from compute shader.
    pub fn draw<'a>(
        &'a self,
        pass: &mut wgpu::RenderPass<'a>,
        uniform_bg: &'a wgpu::BindGroup,
        shadow_bg: &'a wgpu::BindGroup,
        atlas_bg: &'a wgpu::BindGroup,
    ) {
        pass.set_pipeline(&self.render_pipeline);
        pass.set_bind_group(0, uniform_bg, &[]);
        pass.set_bind_group(1, shadow_bg, &[]);
        pass.set_bind_group(2, &self.render_instance_bg, &[]);
        pass.set_bind_group(3, atlas_bg, &[]);
        pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
        pass.set_index_buffer(self.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
        pass.draw_indexed_indirect(&self.indirect_buffer, 0);
    }

    /// Draw tree shadows using indirect draw.
    pub fn draw_shadow<'a>(
        &'a self,
        pass: &mut wgpu::RenderPass<'a>,
        uniform_bg: &'a wgpu::BindGroup,
    ) {
        pass.set_pipeline(&self.shadow_pipeline);
        pass.set_bind_group(0, uniform_bg, &[]);
        pass.set_bind_group(1, &self.shadow_instance_bg, &[]);
        pass.set_vertex_buffer(0, self.vertex_buffer.slice(..));
        pass.set_index_buffer(self.index_buffer.slice(..), wgpu::IndexFormat::Uint32);
        pass.draw_indexed_indirect(&self.indirect_buffer, 0);
    }
}

/// Vertex with position, normal, and per-vertex color (trunk brown, foliage uses placeholder
/// green that gets multiplied by instance foliage_color in the shader).
type TreeVertex = [f32; 9]; // [x, y, z, nx, ny, nz, r, g, b]

/// Generate combined trunk (cylinder) + multi-layered foliage (3 stacked cones) mesh.
/// `segments` controls circular resolution.
fn generate_tree_mesh(segments: u32) -> (Vec<TreeVertex>, Vec<u32>) {
    let trunk_radius = 0.15;
    let trunk_height = 0.5;
    let trunk_color = [0.25, 0.20, 0.10];

    let mut verts: Vec<TreeVertex> = Vec::new();
    let mut indices: Vec<u32> = Vec::new();

    // --- Trunk (open cylinder) — normals are purely radial ---
    let base_idx = verts.len() as u32;
    for i in 0..=segments {
        let theta = (i as f32 / segments as f32) * std::f32::consts::TAU;
        let (cos_t, sin_t) = (theta.cos(), theta.sin());
        let x = trunk_radius * cos_t;
        let z = trunk_radius * sin_t;
        verts.push([x, 0.0, z, cos_t, 0.0, sin_t, trunk_color[0], trunk_color[1], trunk_color[2]]);
    }
    for i in 0..=segments {
        let theta = (i as f32 / segments as f32) * std::f32::consts::TAU;
        let (cos_t, sin_t) = (theta.cos(), theta.sin());
        let x = trunk_radius * cos_t;
        let z = trunk_radius * sin_t;
        verts.push([x, trunk_height, z, cos_t, 0.0, sin_t, trunk_color[0], trunk_color[1], trunk_color[2]]);
    }
    let stride = segments + 1;
    for i in 0..segments {
        let b0 = base_idx + i;
        let b1 = base_idx + i + 1;
        let t0 = base_idx + stride + i;
        let t1 = base_idx + stride + i + 1;
        indices.push(b0);
        indices.push(t0);
        indices.push(b1);
        indices.push(b1);
        indices.push(t0);
        indices.push(t1);
    }

    // --- Foliage: 3 stacked cones (spruce/pine silhouette) ---
    let layers: [(f32, f32, f32, f32); 3] = [
        (0.5, 0.85, 1.3, 0.82),
        (1.1, 0.60, 1.1, 0.91),
        (1.6, 0.35, 0.9, 1.00),
    ];

    for (base_y, radius, height, shade) in layers {
        let tip_y = base_y + height;
        let foliage_color = [shade, shade, shade];

        // Cone surface normal: normalize(radial + up * radius/height)
        let r_over_h = radius / height;
        let inv_len = 1.0 / (1.0 + r_over_h * r_over_h).sqrt();

        // Tip vertex — normal points up
        let tip_idx = verts.len() as u32;
        verts.push([0.0, tip_y, 0.0, 0.0, 1.0, 0.0, foliage_color[0], foliage_color[1], foliage_color[2]]);

        // Side ring vertices with cone surface normals
        let ring_start = verts.len() as u32;
        for i in 0..=segments {
            let theta = (i as f32 / segments as f32) * std::f32::consts::TAU;
            let (cos_t, sin_t) = (theta.cos(), theta.sin());
            let x = radius * cos_t;
            let z = radius * sin_t;
            let nx = cos_t * inv_len;
            let ny = r_over_h * inv_len;
            let nz = sin_t * inv_len;
            verts.push([x, base_y, z, nx, ny, nz, foliage_color[0], foliage_color[1], foliage_color[2]]);
        }

        // Side triangles: tip to ring
        for i in 0..segments {
            indices.push(tip_idx);
            indices.push(ring_start + i);
            indices.push(ring_start + i + 1);
        }

        // Base cap: separate ring with downward normals + center
        let base_ring_start = verts.len() as u32;
        for i in 0..=segments {
            let theta = (i as f32 / segments as f32) * std::f32::consts::TAU;
            let x = radius * theta.cos();
            let z = radius * theta.sin();
            verts.push([x, base_y, z, 0.0, -1.0, 0.0, foliage_color[0], foliage_color[1], foliage_color[2]]);
        }
        let center_idx = verts.len() as u32;
        verts.push([0.0, base_y, 0.0, 0.0, -1.0, 0.0, foliage_color[0], foliage_color[1], foliage_color[2]]);
        for i in 0..segments {
            indices.push(center_idx);
            indices.push(base_ring_start + i);
            indices.push(base_ring_start + i + 1);
        }
    }

    (verts, indices)
}
